auditores_suscerte/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout as deslogeo
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (password_reset,
        password_reset_done, password_reset_confirm,
        password_reset_complete, password_change,
        password_change_done)
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView
from personas.views import PersonalesView
from curriculum.views import (PerfilView,
    EducacionView, LaboralView, CompetenciaView,
    HabilidadView, ConocimientoView, IdiomaView,
    EditarPersonaView, CitasView, CertificacionView,
    CursoView, VerAuditores, EvaluacionView, revisar_acreditaciones,
    AcreditarView, FijarCitaView)
from auth.views import *
from auth.forms import (ValidatingSetPasswordForm,
    ValidatingPasswordChangeForm)
from django.contrib.auth.decorators import login_required
import os


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^clave/reestablecer/?$',
        password_reset,
        {'post_reset_redirect': reverse_lazy('password_reset_done'),
         'template_name': 'auth/password_reset_form.html',
         'email_template_name': 'auth/reset_subject.html'},
        name='password_reset'),

    url(r'^clave/solicitud_envio/?$',
        password_reset_done,
        {'template_name': 'auth/password_reset_done.html'},
        name='password_reset_done'),

    url(r'^clave_cambiada/$',
        password_change_done,
        {'template_name': 'auth/clave_cambiada.html'},
        name='password_change_done'),

    url(r'^clave/confirmacion/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': reverse_lazy('password_reset_complete'),
         'template_name': 'auth/confirmar_cambiar_clave.html',
         'set_password_form': ValidatingSetPasswordForm},
        name='password_reset_confirm'),

    url(r'^clave/reestablcimiento/completo/$',
        password_reset_complete,
        {'template_name': 'auth/clave_cambiada.html'},
        name='password_reset_complete'),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^curriculum/',
        include('curriculum.urls')),

    url(r'logout/',
        deslogeo,
        {'next_page': '/'},
        name='salir'),

    url(r'login/',
        auth,
        name='auth'),

    url(r'cambiar_clave/',
        login_required(password_change),
        {'password_change_form': ValidatingPasswordChangeForm,
        'template_name': 'auth/password_reset_form.html',
        'post_change_redirect': 'logout/',
        'extra_context':
            {'cambiar_clave': True,
             'formulario': True,
             'titulo': u'cambiar contraseña',
             'palabra_clave': 'cambiar'},
        },
        name='cambiar_clave'),

    url(r'^listado_auditores/',
        VerAuditores.as_view(),
        name='listado_auditores'),

    url(r'^perfil/info_personal/*$',
        login_required(EditarPersonaView.as_view()),
        name='info_personal'),

    url(r'^perfil/citas/*$',
        login_required(CitasView.as_view()),
        name='citas'),

    url(r'^perfil/educacion/(?P<palabra>\w+)/(?P<educacion_id>[\d]+)*$',
        login_required(EducacionView.as_view()),
        name='educacion'),

    url(r'^perfil/laboral/(?P<palabra>\w+)/(?P<laboral_id>[\d]+)*$',
        login_required(LaboralView.as_view()),
        name='laboral'),

    url(r'^perfil/conocimiento/(?P<palabra>\w+)/(?P<conocimiento_id>[\d]+)*$',
        login_required(ConocimientoView.as_view()),
        name='conocimiento'),

    url(r'^perfil/evaluacion/(?P<aspirante_id>[\d]+)/',
        login_required(EvaluacionView.as_view()),
        name='evaluacion'),

    url(r'^perfil/competencia/(?P<aspirante_id>[\d]+)/',
        login_required(CompetenciaView.as_view()),
        name='competencia'),

    url(r'^perfil/habilidad/(?P<palabra>\w+)/(?P<habilidad_id>[\d]+)*$',
        login_required(HabilidadView.as_view()),
        name='habilidad'),

    url(r'^perfil/idioma/(?P<palabra>\w+)/(?P<idioma_id>[\d]+)*$',
        login_required(IdiomaView.as_view()),
        name='idioma'),

    url(r'^perfil/curso/(?P<palabra>\w+)/(?P<curso_id>[\d]+)*$',
        login_required(CursoView.as_view()),
        name='curso'),

    url(r'^perfil/certificacion/(?P<palabra>\w+)/(?P<certificacion_id>[\d]+)*$',
        login_required(CertificacionView.as_view()),
        name='certificacion'),

    url(r'^perfil/$',
        login_required(PerfilView.as_view()),
        name='perfil'),

    url(r'^revisar_acreditaciones/$',
        'curriculum.views.revisar_acreditaciones',
        name='revisar_acreditaciones'),

    url(r'^acreditar/(?P<usuario_id>[\d]+)*$',
        login_required(AcreditarView.as_view()),
        name='acreditar'),

    url(r'^fijar_cita/(?P<usuario_id>[\d]+)*$',
        login_required(FijarCitaView.as_view()),
        name='acreditar'),

    url(r'^$',
        auth, name='inicio'),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
    {'document_root': os.path.join(os.path.dirname(__file__), 'static')}),
    )

curriculum/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from curriculum.views import *
from curriculum.forms import * 
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'auditores_suscerte.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^postulacion/$', login_required(
            CurriculumView.as_view()), name='curriculum'),
)

curriculum/models.py
# -*- coding: UTF8 -*-
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.contenttypes.models import ContentType
from django.contrib.admin.models import LogEntry, ADDITION, DELETION, CHANGE
from django.contrib import messages
from django.core.mail import send_mail
from personas.models import Persona
from lugares.models import Estado, Institucion, Pais
from auth.models import UserProfile
from auditores_suscerte import settings
from auth.models import Mensaje

# Modelos para construir el Curriculum

NIVELES_COMPETENCIA = (
        ('experto', 'Experto'),
        ('alto', 'Alto'),
        ('medio', 'Medio'),
        ('basico', u'Básico'),
        ('nada', 'Nada'),
        )


class Certificacion(models.Model):
    '''
    Modelo que registra cada uno de
    los certificados de la persona
    '''
    persona = models.ForeignKey(Persona)
    titulo = models.CharField(max_length=500, verbose_name=u'título')
    codigo_certificacion = models.CharField(max_length=30,
            blank=True,
            verbose_name=u'código de certificación')
    institucion = models.ForeignKey(Institucion, verbose_name=u'institución')
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(blank=True)
    pais = models.ForeignKey(Pais)

    class Meta:
        db_table = u'certificacion'
        verbose_name = u'certificación'
        verbose_name_plural = 'certificaciones'

    def __unicode__(self):
        return u'%s - %s' % (self.persona, self.titulo)

OPCIONES_CITAS = (('primera_fecha', 'Primera fecha'),
                  ('segunda_fecha', 'Segunda fecha'),
                  ('tercera_fecha', 'Tercera fecha'))


class Cita(models.Model):
    usuario = models.ForeignKey(UserProfile)
    primera_fecha = models.DateField()
    segunda_fecha = models.DateField()
    tercera_fecha = models.DateField()
    cita_fijada = models.CharField(max_length=15,
            choices=OPCIONES_CITAS, blank=True)

    class Meta:
        db_table = u'cita'

    def __unicode__(self):
        return u'%s' % (self.usuario)


@receiver(post_save, sender=Cita)
def post_save_cita(sender, **kwargs):
    '''
    Función para procesar antes de guardar en base de datos
    '''
    cita = kwargs['instance']

    citas = Cita.objects.filter(
            usuario=cita.usuario,
            primera_fecha=cita.primera_fecha,
            segunda_fecha=cita.segunda_fecha,
            tercera_fecha=cita.tercera_fecha)

    if cita.cita_fijada == None or cita.cita_fijada == '':
        # Si no hay una fecha fijada aún,
        # se envía un mail a los admin
        asunto = u'Nueva propuesta de cita de %s' % (cita.usuario)
        emisor = settings.EMAIL_HOST_USER
        destinatarios = settings.MANAGERS
        mensaje = 'Ha llegado una nueva solicitud de cita para entrevista,'
        mensaje += ' por lo que este correo le ha llegado a los managers'
        mensaje += ' para definir su fecha. Ahora mismo puede revisar la '
        mensaje += 'propuesta en: '
        mensaje += '%s/admin/curriculum/cita/%s/.' % (settings.HOST, cita.id)
    else:
        # Si hay una fecha fijada, se envía un mail
        # al usuario indicándole la fecha definitiva
        asunto = u'%sFijada fecha para cita' % (settings.EMAIL_SUBJECT_PREFIX)
        emisor = settings.EMAIL_HOST_USER
        destinatarios = [cita.usuario.user.email]

        # Búsqueda de fecha definitiva:
        fecha_fijada = ''
        if cita.cita_fijada == 'primera_fecha':
            fecha_fijada = cita.primera_fecha
        elif cita.cita_fijada == 'segunda_fecha':
            fecha_fijada = cita.segunda_fecha
        else:
            fecha_fijada = cita.tercera_fecha

        # Envío de mail
        mensaje = Mensaje.objects.get(caso='Postulación de cita')

        # Sustitución de variables clave y usuario
        mensaje = mensaje.mensaje.replace('<fecha>','%s'%(fecha_fijada))

    send_mail(subject=asunto, message=mensaje,
                from_email=settings.DEFAULT_FROM_EMAIL, recipient_list=destinatarios)


class ListaIdiomas(models.Model):
    nombre = models.CharField(max_length=20)

    class Meta:
        db_table = u'lista_idiomas'
        verbose_name = 'lista de idiomas'
        verbose_name_plural = 'lista de idiomas'

    def __unicode__(self):
        return u'%s' % (self.nombre)

NIVEL_IDIOMA = (('4', 'Fluido'),
                ('3', 'Alto'),
                ('2', 'Medio'),
                ('1', 'Bajo'))


class Idioma(models.Model):
    persona = models.ForeignKey(Persona)
    idioma = models.ForeignKey('ListaIdiomas')
    nivel_leido = models.CharField(max_length=10,
            choices=NIVEL_IDIOMA,
            verbose_name=u'nivel de lectura')
    nivel_escrito = models.CharField(max_length=10,
            choices=NIVEL_IDIOMA,
            verbose_name=u'nivel de escritura')
    nivel_hablado = models.CharField(max_length=10,
            choices=NIVEL_IDIOMA,
            verbose_name=u'Fluidez de conversación')

    class Meta:
        db_table = u'idioma'
        ordering = ('-idioma',)

    def __unicode__(self):
        return u'%s' % (self.idioma)


class Conocimiento(models.Model):
    usuario = models.ForeignKey(UserProfile)
    otros_conocimientos = models.TextField(
            help_text=u'Escriba aquí los conocimientos extras')

    class Meta:
        db_table = 'conocimiento'

    def __unicode__(self):
        return u'%s' % (self.otros_conocimientos)


class Habilidad(models.Model):
    usuario = models.ForeignKey(UserProfile)
    habilidad = models.CharField(max_length=50)

    class Meta:
        db_table = 'habilidad'
        verbose_name_plural = 'habilidades'

    def __unicode__(self):
        return u'%s' % (self.habilidad)

TIPO_CONOCIMIENTO = (
            ('academico', u'Nivel Académico'),
            ('basico', u'Conocimiento Básico'),
            ('complementario', 'Conocimiento Complementario'),
            ('requerido', 'Conocimiento Requerido'))


class TipoCompetencia(models.Model):
    nombre = models.CharField(max_length=50)
    puntaje_maximo = models.FloatField(verbose_name=u'puntaje máximo')

    class Meta:
        db_table = 'tipo_competencia'
        verbose_name = 'tipo de competencia'
        verbose_name_plural = 'tipos de competencias'

    def __unicode__(self):
        return u'%s' % (self.nombre)

TIPOS_PUNTAJE = (('int', 'Cantidades'), ('float', 'Puntos'))


class ListaCompetencia(models.Model):
    nombre = models.CharField(max_length=200)
    tipo = models.ForeignKey(TipoCompetencia)
    puntaje_maximo = models.FloatField(verbose_name=u'puntaje máximo')
    puntaje_minimo = models.FloatField(verbose_name=u'puntaje mínimo',
            default=0.0)
    tipo_puntaje = models.CharField(max_length=10, choices=TIPOS_PUNTAJE)

    class Meta:
        db_table = 'lista_competencia'
        verbose_name = 'lista de competancia'
        verbose_name_plural = 'lista de competancias'

    def __unicode__(self):
        return u'%s' % (self.nombre)


class Competencia(models.Model):
    usuario = models.ForeignKey(UserProfile)
    tipo = models.ForeignKey('TipoCompetencia')
    puntaje = models.FloatField()
    fecha = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'competencia'

    def __unicode__(self):
        return u'%s' % (self.tipo)


class Aprobacion(models.Model):
    '''
    Clase para definir puntajes de aprobación
    tanto para evaluación como entrevista
    '''
    entrevista_maxima = models.FloatField(
            verbose_name='entrevista máxima',
            help_text=u'defina putuación máxima')
    entrevista_aprobatoria = models.FloatField(
            help_text=u'defina putuación mínima aprobatoria')
    evaluacion_maxima = models.FloatField(
            verbose_name='evaluación máxima',
            help_text=u'defina putuación máxima')
    evaluacion_aprobatoria = models.FloatField(
            verbose_name='evaluación aprobatoria',
            help_text=u'defina putuación mínima aprobatoria')

    class Meta:
        db_table = 'aprobacion'
        verbose_name = u'aprobación'
        verbose_name_plural = 'aprobaciones'
        get_latest_by = 'fecha'

    def __unicode__(self):
        return u'Entrevistas: %s/%s. \
                Evaluaciones: %s/%s' % (self.entrevista_aprobatoria,
                self.entrevista_maxima, self.evaluacion_aprobatoria,
                self.evaluacion_maxima)


class Evaluacion(models.Model):
    usuario = models.ForeignKey(UserProfile)
    puntaje = models.FloatField()
    fecha = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'evaluacion'
        verbose_name = u'evaluación'
        verbose_name_plural = u'evaluaciones'

    def __unicode__(self):
        return u'%s' % (self.usuario)


class Curso(models.Model):
    usuario = models.ForeignKey(UserProfile)
    titulo = models.CharField(max_length=150, verbose_name=u'título')
    institucion = models.ForeignKey(Institucion, verbose_name=u'institución')
    estado = models.ForeignKey(Estado)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    horas = models.PositiveIntegerField()

    class Meta:
        db_table = 'curso'

    def __unicode__(self):
        return u'%s: %s' % (self.usuario, self.titulo)


class Laboral(models.Model):
    usuario = models.ForeignKey(UserProfile)
    empresa = models.CharField(max_length=100)
    sector = models.CharField(max_length=60,
            help_text=u'Financiero, Industrial, Tecnológico, entre otros.')
    estado = models.ForeignKey(Estado)
    telefono = models.CharField(max_length=15, verbose_name=u'teléfono')
    cargo = models.CharField(max_length=60)
    funcion = models.TextField(verbose_name=u'función',
            help_text=u'indique la función o funciones que desempeñaba')
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField(null=True)
    trabajo_actual = models.BooleanField()

main/templates/perfil/informacion_personal.html
{% load humanize %} 

{% load static %}
{% get_static_prefix as directorio %}
<nav class="ink-navigation" data-offset-top="65px" data-offset-bottom="200px" id="forms_menu">
<div class="box">
    <div class="content-center">
        <img src='{{ directorio }}images/avatar.png'>
        <h3><span class="tooltip ink-label" data-tip-text="Editar" data-tip-where="mousefix" data-tip-color="blue"><a href="{% url 'info_personal' %}" class="ink-button blue" style="padding:0px 12px"><span class="icon-pencil"></span></a></span>{{ persona.primer_nombre }} {{ persona.primer_apellido }}</h3>
    </div>
    C.I.: {{ persona.cedula|intcomma }} <br />
    Género: 
	{% ifequal persona.genero 0 %}
	    Masculino
	{% else %}
	    Femenino
	{% endifequal %}
    <br />
    Dirección: {{ persona.direccion }}<br />
    Teléfono:
	    {% ifequal persona.tlf_contacto 'fijo' %}
		{{ persona.tlf_reside }}
	    {% endifequal %}
	    {% ifequal persona.tlf_contacto 'oficina' %}
		{{ persona.oficina }}
	    {% endifequal %}
	    {% ifequal persona.tlf_contacto 'movil' %}
		{{ persona.movil }}
	    {% endifequal %}
    <br />
    Estado civil:
	    {% ifequal persona.estado_civil 's' %}
		Solter{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
	    {% endifequal %}
	    {% ifequal persona.estado_civil 'c' %}
		Casad{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
	    {% endifequal %}
	    {% ifequal persona.estado_civil 'd' %}
		Divorciad{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
	    {% endifequal %}
	    {% ifequal persona.estado_civil 'v' %}
		Viud{% ifequal persona.genero 0 %}o{% else %}a{% endifequal %}
	    {% endifequal %}
    <br />
    Email: <a href="mailto:{{ persona.email }}">{{ persona.email }}</a>
    <br />

</div>

main/templates/perfil/perfil_operador.html
{% include "base_ink.html" %}

{% block personales %}

<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
  <body>

{% load static %}
{% load humanize %} 
{% load perfil %}
 
  <!-- Main Page Content and Sidebar -->
  
<div class="ink-grid">
    {% include 'menu_perfil.html' %}

    <div class="space">
        {% if mensaje %}
            <div class="ink-alert basic {{ tipo_mensaje }}">
                <button class="ink-dismiss" id="cerrar">&times;</button>
                <p>{{ mensaje }}</p>
            </div>
        {% endif %}
        <div class="column-group gutters">
            <div class="large-30 medium-100 small-100 push-left">
                {% include "perfil/informacion_personal.html" %}
            </div>
            <div class="large-70 medium-100 small-100 push-right">
                <div class="box">
                    <section id="aspirantes">
                        <h4><div class="ink-titulo_superior"><i class="icon-check-minus"></i> Aspirantes a auditores</div></h4>
                        {% if aspirantes %}
                            <form class="ink-form" method="post">{% csrf_token %}
                            <div class="column-group push-center">
                                <nav class="ink-navigation">
                                    <ul class="pagination shadowed rounded blue push-right small">
                                    {% if aspirantes.has_previous %}
                                        <li class="previous"><a href="?page={{ aspirantes.previous_page_number }}">Anterior</a></li>
                                    {% else %}
                                        <li class="previous disabled"><a href="#">Anterior</a></li>
                                    {% endif %}

                                    <li>
                                        <a href="#">{{ aspirantes.number }}/{{ aspirantes.paginator.num_pages }}</a>
                                    </li>

                                    {% if aspirantes.has_next %}
                                        <li class="next"><a href="?page={{ aspirantes.next_page_number }}">Sigueinte</a></li>
                                    {% else %}
                                        <li class="next disabled"><a href="#">Sigueinte</a></li>
                                    {% endif %}
                                    </ul>
                                </nav>
                            </div>

                            <table class="ink-table hover" width="100%">
                                <tbody>
                                <thead class="small">
                                        <th>Cédula</th>
                                        <th>Nombres</th>
                                        <th>Apellidos</th>
                                        {% if not aspirante.get_profile.entrevista_set.get_query_set.exists %}
                                            <th>Entrevista</th>
                                        {% endif %}
                                        {% if not aspirante.get_profile.evaluacion_set.get_query_set.exists %}
                                            <th>Evaluación</th>
                                        {% endif %}
                                </thead>
                                <tbody>
                                    {% for aspirante in aspirantes %}
                                    <tr align="center">
                                        <td>{{ aspirante.profile.persona.cedula }} 
                                        <td>{{ aspirante.profile.persona.primer_nombre }} {{ auditor.profile.persona.segundo_nombre }}</td>
                                        <td>{{ aspirante.profile.persona.primer_apellido }} {{ auditor.profile.persona.segundo_apellido }}</td>
                                            <td>
                                                {% ifnotequal aspirante.get_profile.cita_set.get_query_set.last.cita_fijada '' %}
                                                    {% if aspirante.id|puntaje_entrevistado %}
                                                        {{ aspirante.id|puntaje_entrevistado }}
                                                    {% else %}
                                                        <a href="{% url 'competencia' aspirante.id %}" class="ink-button blue">
                                                            <span class="tooltip ink-label" data-tip-text="Cargar calificaciones" data-tip-where="mousefix" data-tip-color="blue">
                                                                <i class="icon-file-text"></i>
                                                            </span>
                                                        </a>
                                                    {% endif %}
                                                {% else %}
                                                    Fije la cita
                                                {% endifnotequal %}
                                            </td>
                                            <td>
                                                {% ifnotequal aspirante.get_profile.cita_set.get_query_set.last.cita_fijada '' %}
                                                    {% if aspirante.get_profile.evaluacion_set.get_query_set.last.puntaje %}
                                                        {{ aspirante.get_profile.evaluacion_set.get_query_set.last.puntaje }}
                                                    {% else %}
                                                        <a href="{% url 'evaluacion' aspirante.id %}" class="ink-button blue">
                                                            <span class="tooltip ink-label" data-tip-text="Cargar calificaciones" data-tip-where="mousefix" data-tip-color="blue">
                                                                <i class="icon-book"></i>
                                                            </span>
                                                        </a>
                                                    {% endif %}
                                                {% else %}
                                                    Fije la cita
                                                {% endifnotequal %}
                                            </td>
                                            <td>
                                            {% ifnotequal aspirante.get_profile.cita_set.get_query_set.last.cita_fijada '' %}
                                                {% if aspirante.get_profile.evaluacion_set.get_query_set.exists %}
                                                    <a href="{% url 'acreditar' aspirante.id %}">Acreditar</a>
                                                {% else %}
                                                    Fije puntajes
                                                {% endif %}
                                            {% else %}
                                                <a href="{% url 'acreditar' aspirante.id %}">Fijar cita</a>
                                            {% endifnotequal %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            </form>
                        {% else %}
                            <p>Por ahora no hay ningún aspirante al registro como auditor.<p>
                        {% endif %}
                    </section>
                </div>
                <div class="box">
                    <section id="auditores">
                        <h4><div class="ink-titulo_superior"><i class="icon-check"></i> Auditores registrados</div></h4>
                        <form class="ink-form" method="post">{% csrf_token %}
                        <div class="column-group push-center">
                            <nav class="ink-navigation">
                                <ul class="pagination shadowed rounded blue push-right small">
                                {% if auditores.has_previous %}
                                    <li class="previous"><a href="?page={{ auditores.previous_page_number }}">Anterior</a></li>
                                {% else %}
                                    <li class="previous disabled"><a href="#">Anterior</a></li>
                                {% endif %}

                                <li>
                                    <a href="#">{{ auditores.number }}/{{ auditores.paginator.num_pages }}</a>
                                </li>

                                {% if auditores.has_next %}
                                    <li class="next"><a href="?page={{ auditores.next_page_number }}">Sigueinte</a></li>
                                {% else %}
                                    <li class="next disabled"><a href="#">Sigueinte</a></li>
                                {% endif %}
                                </ul>
                            </nav>
                        </div>

                        <table class="ink-table hover" width="100%">
                            <thead class="small">
                                    <th>#</th>
                                    <th>Nombres</th>
                                    <th>Acreditado</th>
                                    <th>Vence en</th>
                                    <th>TLF</th>
                                    <th>Email</th>
                            </thead>
                            <tbody>
                                {% for auditor in auditores %}
                                <tr align="center">
                                    <td>{{ auditor.id }}</td>
                                    <td>{{ auditor.persona.primer_nombre }} {{ auditor.persona.primer_apellido }}</td>
                                    <td>{{ auditor.fecha_acreditacion|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>{{ auditor.fecha_desacreditacion|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>
                                        {% ifequal persona.tlf_contacto 'fijo' %}
                                            {{ persona.tlf_reside }}
                                        {% endifequal %}
                                        {% ifequal persona.tlf_contacto 'oficina' %}
                                            {{ persona.oficina }}
                                        {% endifequal %}
                                        {% ifequal persona.tlf_contacto 'movil' %}
                                            {{ persona.movil }}
                                        {% endifequal %}
                                    </td>
                                    <td>{{ auditor.persona.email|mail_antispam }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %} 

  </body>
</html>
{% endblock %}